FROM bitwalker/alpine-erlang:19.2.1b

RUN apk update && \
    apk --no-cache --update add libgcc libstdc++ && \
    rm -rf /var/cache/apk/*

EXPOSE 8443
ENV HTTPS_PORT=8443 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

ADD mongoose_push.tar.gz ./
RUN chown -R default ./releases

USER default

ENTRYPOINT ["/opt/app/bin/mongoose_push"]
